default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-184-73-196-82.compute-1.amazonaws.com
  database: d6o3dokg7jvk0i
  username: zsxlcophzmlkhr
  password: PJMzUdW_dka2VXQFjTcE9gTMZz
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
