default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: rails_myapp
  port: 3306
  username: root
  password: onodera1Love
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
